#!/bin/bash

image=ocr2021
home=$(pwd)
test -f ./config.sh && source ./config.sh

docker run \
    $runtime \
    --ipc host \
    --network host \
    --rm \
    -v /etc/sudoers:/etc/sudoers \
    -v /etc/passwd:/etc/passwd \
    -v /etc/group:/etc/group \
    -v $home:$HOME \
    -v `pwd`:`pwd` \
    $opts \
    -w `pwd` \
    -u $(id -u):$(id -g) \
    -i \
    -e JUPYTER_CONFIG_DIR=$(pwd)/.jupyter \
    -e JUPYTER_DATA_DIR=$(pwd)/.jupyter-data \
    -e JUPYTER_DATA_DIR=$(pwd)/.jupyter-runtime \
    -t "$image" \
    jupyter "$@"
