FROM ocr2021-base

RUN pip3 install -e git+git://github.com/tmbdev/webdataset.git#egg=webdataset
RUN pip3 install -e git+git://github.com/NVlabs/ocrodeg.git#egg=ocrodeg
RUN pip3 install -e git+git://github.com/NVlabs/tensorcom.git#egg=tensorcom
RUN pip3 install -e git+git://github.com/tmbdev/tarproc.git#egg=tarproc
RUN pip3 install -e git+git://github.com/tmbdev/torchmore.git#egg=torchmore
RUN pip3 install -e git+git://github.com/ocropus/ocropus4.git#egg=ocropus
